### ISSUE TITLE
Full Screen Crash

### ISSUE THREAD

**Issue by Watchful1** [dan200/Redirection#31]
Windows 7, NVIDIA NVS 4200M

Clicking the full screen button, double clicking the top of the window or selecting full screen in options crashes the game. With the last option, once the game is started again it opens in full screen without problems, but unselecting full screen then also crashes the game.

```
Redirection 0.6.2.1
Developed by Daniel Ratcliffe (dratcliffe@gmail.com)
SDL version: 2.0.3
Platform: Windows (Windows)
Steamworks not requested
Trying to use language en_US
Using language en (English)
Creating window sized 845x480
Loaded level levels/empty.level
Loaded level levels/startscreen.level
Resolution changed to 1280x720
Game crashed with Dan200.Core.Main.OpenGLException: InvalidFramebufferOperationExt
   at Dan200.Core.Main.App.CheckOpenGLError()
   at Dan200.Game.Game.Game.Render()
   at Dan200.Core.Main.App.Run[TGame](GameInfo info, String[] args)
Game shutdown
```

**Comment by dan200** [comment]
Possibly fixed. It at least won't throw an exception anymore. Could you check this in the next version (should be a few weeks from now)?
