### ISSUE TITLE
Rendering issue with resized window

### ISSUE THREAD

**Issue by Felix246** [dan200/Redirection#39]
The game started in 845x480 resolution. When now making it bigger in any direction, some parts of the window are black. When sizing it back to 845x480 or smaller it looks normal. After around 30 secons my PC crashed totally with the window being fullsized (not fullscreen).
![unbenannt](https://cloud.githubusercontent.com/assets/5970076/4873189/0e07d144-6205-11e4-92c7-cdd8f58bf3ee.PNG)
PC specs:
- windows 7
- ATI Mobility Radeon HD 5650 GPU
- Intel Core i5 M460 CPU

Redirection v0.6.4

**Comment by dan200** [comment]
Please retry in the latest build!
