### ISSUE TITLE
"Redirection stopped working" on launch

### ISSUE THREAD

**Issue by matthijsvdmeulen** [dan200/Redirection#45]
hey dan,

I have an weird issue when trying to launch redirection,
windows says "Redirection has stopped working" and gives the following error:

Probleemhandtekening:
  Gebeurtenisnaam van probleem: CLR20r3
  Probleemhandtekening 01:  redirection.exe
  Probleemhandtekening 02:  1.0.0.0
  Probleemhandtekening 03:  54550381
  Probleemhandtekening 04:  SDL2-CS
  Probleemhandtekening 05:  0.0.0.0
  Probleemhandtekening 06:  536fa99f
  Probleemhandtekening 07:  1d43
  Probleemhandtekening 08:  0
  Probleemhandtekening 09:  System.AccessViolationException
  Versie van besturingssysteem: 6.1.7601.2.1.0.256.1
  Landinstelling-id:    1043
  Aanvullende informatie 1: 0a9e
  Aanvullende informatie 2: 0a9e372d3b4ad19135b953a78882e789
  Aanvullende informatie 3: 0a9e
  Aanvullende informatie 4: 0a9e372d3b4ad19135b953a78882e789

Its dutch, so ill try to translate the sentences:

Probleemhandtekening = problemsignature
Gebeurtenisnaam van probleem = eventname of problem
Versie van besturingssysteem = operating system version
Landinstelling-id = countrysetting-id
 Aanvullende informatie = additional information

and the redirection log:

Logging to C:\Users\meulen\AppData\Roaming\Redirection\logs\2014-12-22T00-25-41.txt
Redirection 0.6.4
Developed by Daniel Ratcliffe (dratcliffe@gmail.com)
SDL version: 2.0.3
Platform: Windows (Windows)
Steamworks not requested
Trying to use language nl_NL
Using language nl (Dutch)
Creating window sized 845x480

I don't know how to reproduce it, on all my other pc's it works fine.

at last, a simple screenshot
![redirection](https://cloud.githubusercontent.com/assets/8491412/5520075/e13419f8-8972-11e4-9db7-82bf74d503c1.png)

I hope you can do something with this info, its all I could gather.

yours sincerely,

Matthijs van der Meulen

**Comment by dan200** [comment]
Please retry in the final build (1.0.7), i suspect this is fixed now!
