### ISSUE TITLE
Negative Number Blocks

### ISSUE THREAD

**Issue by tauqua** [dan200/Redirection#46]
In the Act II stage Perimeter (The first stage I came across it, although this may be an issue elsewhere), you can go into negative blocks.

To replicate;
Go into Act II, Perimeter
Place your two given blocks anywhere
Try to place more blocks on the green striped platforms (raised or lowered doesn't matter)

Here's images to explain more. http://imgur.com/a/WpsAR

**Comment by dan200** [comment]
Fixed
