### ISSUE TITLE
Not starting on OSX

### ISSUE THREAD

**Issue by PunKeel** [dan200/Redirection#47]
Hi,
The redirection launcher won't start. No window, no in-console error when launched using `open`
Only Console.app error is: 
`12/09/15 8:55:45,321 pm com.apple.xpc.launchd[1]: (RedirectionLauncher.114484[21614]) Service exited with abnormal code: 127`

I don't know where to find logs, if it doesn't seem to log anything :)

**Comment by dan200** [comment]
Hmm, have you installed mono per the instructions?

**Comment by PunKeel** [comment]
Absolutely not,
Who reads manuals nowadays? ;D

**Comment by dan200** [comment]
Can I mark this as fixed? The next version of the launcher will have clear
messaging if mono is missing
