### ISSUE TITLE
Arcade throws C# stacktrace when attempting to dofile backwards paths

### ISSUE THREAD

**Issue by incinirate** [dan200/Redirection#49]
When attempting the following code, the Redirection arcade throws the following C# stacktrace:
`dofile("../anything")`
[Stacktrace](https://inci.ninja/imgs/oh6g0z.png)
This shouldn't throw any C# stacktrace, and instead show an error something along the lines of "Attempt to access invalid path"

**Comment by dan200** [comment]
Reproduced and fixed for v1.1.0. Thanks!
