### ISSUE TITLE
gpu.drawBox errors when x > 57

### ISSUE THREAD

**Issue by incinirate** [dan200/Redirection#50]
This one doesn't even make sense to me, but whenever I call gpu.drawBox where the starting X is greater than 57, it throws a C# stacktrace. It doesn't even make sense because 58+ is not even outside of the screen boundaries, its about 5 pixels inside actually. Anyways, here is the [stacktrace](https://inci.ninja/imgs/oh9sk0.png)
The specific line of code I used was this:
`gpu.drawBox(58, 14, 2, 7, 1)`

**Comment by dan200** [comment]
Fixed for 1.1.0! Thanks! The code wasn't bound-checking the right-hand-side of the box correctly, so it was writing beyond the edge of the image. Let me know if you find anything similar!

**Comment by dan200** [comment]
Actually: that description isn't accurate: What was actually happening is it was checking if "x + height" was beyond the image, instead of "x + width", so the call was failing when it shouldn't have. Either way, the typo is now fixed :)
