### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by Michagogo** [dan200/Redirection#51]
I just had the game crash twice. The first time, at the second paragraph of the opening crawl.

Log:
```
Redirection 1.0.7 (Steam build)
Developed by Daniel Ratcliffe (dratcliffe@gmail.com)
Platform: Windows (Windows)
Steamworks initialised
SDL version: 2.0.3
SDL2 Initialised
SDL2_Image initialised
Logging to C:\Program Files (x86)\Steam\userdata\42174739\305760\local\logs\2016-12-08T21-53-34.txt
Loaded gamepad mappings from gamecontrollerdb.txt
Creating fullscreen window
GL Vendor: Intel
GL Version: 3.3.0 - Build 8.15.10.2626
GLSL Version: 3.30 - Intel Build 8.15.10.2626
Adaptive VSync enabled
Adding early assets
Loaded 38 assets
Using language debug (Debug)
Adding base assets
Adding main assets
Adding temp assets
Resolution changed to 1366x768 (AA:FXAA)
Loaded 999 assets
Using language en (English)
```

And the second time, after skipping said intro, it froze as the animation for placing the first tutorial obstacle was playing, and crashed. Log is completely identical, other than the timestamp on the file and this one extra line at the end:
`Unlocked achievement complete_first_level`

**Comment by Michagogo** [comment]
The game didn't grey out or pop up a Windows "has stopped working" box or anything -- it just closed, as if I'd quit it myself.

**Comment by dan200** [comment]
Hmm. Mysterious! What are your system specs?

**Comment by Michagogo** [comment]
HP Pavilion dv6t-7000 Quad Edition. Intel Core i7-3610QM, GeForce 630M with
1GB (I think?) VRAM, 16GB RAM, 1TB SanDisk SSD.
Windows 7, 64 bit.
Anything else I'm forgetting?

**Comment by dan200** [comment]
Yeah, that machine definitely shouldn't have any trouble running the game! I'm afraid i'm lost for ideas here. I won't be offended if you want to grab a Steam Refund :/

**Comment by Michagogo** [comment]
I didn't actually get it through Steam. Is there some kind of super-verbose
debug mode that could help narrow it down?

**Comment by dan200** [comment]
How did you get the game?

**Comment by Michagogo** [comment]
I got it way back through itch.io (IIRC), and forgot about it, then
(somewhat) recently I got an email inviting me to get it through Steam.

**Comment by Michagogo** [comment]
Is there any way to get into some kind of debug mode, or more verbose logging, or something? I'd really like to play the game :-(

**Comment by Michagogo** [comment]
Update: I checked Event Viewer, and found 2 Error events being generated in the Application log each time I tried to launch the game and had it crash. The top one has "Application Error" as the source, and the text is:
`Faulting application name: Redirection.exe, version: 1.0.7.0, time stamp: 0x00000000
Faulting module name: ig7icd32.dll, version: 0.0.0.0, time stamp: 0x4f175ce4
Exception code: 0xc0000005
Fault offset: 0x0039ce8c
Faulting process id: 0x8524
Faulting application start time: 0x01d254960b4ef4dc
Faulting application path: C:\Program Files (x86)\Steam\steamapps\common\Redirection\Redirection.exe
Faulting module path: C:\Windows\system32\ig7icd32.dll
Report Id: 4eeea082-c089-11e6-95ab-a0b3cc4c4e7d`

The second one is from ".NET Runtime", and the text is:
`Application: Redirection.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Graphics.OpenGL.GL.BindBuffer(OpenTK.Graphics.OpenGL.BufferTarget, Int32)
   at Dan200.Core.Render.Geometry.DrawRange(Int32, Int32)
   at Dan200.Game.Game.Game.Render()
   at Dan200.Core.Main.App.Run[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Dan200.Core.Main.GameInfo, System.String[])
   at Dan200.Game.Main.Program.Main(System.String[])

`

**Comment by dan200** [comment]
Are your graphics drivers up to date?

**Comment by Michagogo** [comment]
I think it usually updates automatically -- Device Manager says I have
version 21.21.13.7319, dated 10/20/2016. There's a "Update Driver" button,
I'll try that...

**Comment by Michagogo** [comment]
Um. The "Update Driver" button "updated" to 10.18.13.5362, dated 7/22/2015. o_O

**Comment by dan200** [comment]
I suggest getting the latest official drivers from nvidia

**Comment by Michagogo** [comment]
And it's still crashing.

**Comment by Michagogo** [comment]
Ah, okay. I'll try that now.

**Comment by dan200** [comment]
Any luck?

**Comment by Michagogo** [comment]
No, looks like it's still happening. Same error.

**Comment by Michagogo** [comment]
Just got the new update. It crashed once, then a second time it froze as it looked like it was supposed to expand from the middle into the opening screen, with a light blue rectangle in the middle with the border flickering. When I alt-tabbed out and back, it was just a black screen. The music was playing, and I think there were sounds as I moved the mouse around. I closed it and launched again, and it crashed. The two crashes had the same thing in the event logs: a .NET Runtime error:
```
Application: Redirection.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Graphics.OpenGL.GL.BindBuffer(OpenTK.Graphics.OpenGL.BufferTarget, Int32)
   at Dan200.Core.Render.Geometry.DrawRange(Int32, Int32)
   at Dan200.Game.Game.Game.Render()
   at Dan200.Core.Main.App.Run[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Dan200.Core.Main.GameInfo, System.String[])
   at Dan200.Game.Main.Program.Main(System.String[])

```

And an Application Error:
```
Faulting application name: Redirection.exe, version: 1.1.1.0, time stamp: 0x00000000
Faulting module name: ig7icd32.dll, version: 0.0.0.0, time stamp: 0x4f175ce4
Exception code: 0xc0000005
Fault offset: 0x0039ce8c
Faulting process id: 0xb0c
Faulting application start time: 0x01d27807ae8ad758
Faulting application path: C:\Program Files (x86)\Steam\steamapps\common\Redirection\Redirection.exe
Faulting module path: C:\Windows\system32\ig7icd32.dll
Report Id: f2232fe3-e3fa-11e6-b4b4-5cf3707aab9b
```

**Comment by dan200** [comment]
All I guess from this log is it's something to do with your OpenGL drivers. If they're all up to date, I don't know what else to suggest :/

**Comment by dan200** [comment]
If you said the game didn't crash before it went fullscreen, you could try editing Steam\userdata\<youruserid>\305760\local\settings.txt and setting video.fullscreen=false

**Comment by Michagogo** [comment]
Update! I had the latest NVidia drivers installed, but not the latest Intel drivers! Updated those and it works!

**Comment by Michagogo** [comment]
Sorry to have bothered you over this... All's well that ends well, though?

**Comment by dan200** [comment]
Yay! Glad it all worked out. As I said I was stumped for ideas for what to try next. Home the game is worth the wait!
