### ISSUE TITLE
Launching on Linux causes crash

### ISSUE THREAD

**Issue by coolacid** [dan200/Redirection#52]
Launching from Steam on Linux (Ubuntu)

```
Redirection 1.1.0 (Steam build)
Developed by Daniel Ratcliffe (dratcliffe@gmail.com)
Platform: Linux (Linux)
Game crashed with Dan200.Core.Main.SteamworksException: SteamAPI.Init failed.
  at Dan200.Core.Main.App.CheckSteamworksResult (System.String functionName, Boolean result) [0x00000] in <filename unknown>:0
  at Dan200.Core.Main.App.Run[Game] (Dan200.Core.Main.GameInfo info, System.String[] args) [0x00000] in <filename unknown>:0
Logging to log.txt
Closing log file
```

Deleted and reinstalled, same issue.

**Comment by dan200** [comment]
Try restarting steam

**Comment by dan200** [comment]
Any luck?

**Comment by dan200** [comment]
Closing due to no response. For anyone else having this problem, this can be solved by restarting Steam. More info here:
http://steamcommunity.com/app/305760/discussions/3/305510202675613142/

**Comment by coolacid** [comment]
Stupid Github not sending me notices. Yes, I can confirm this appear to solve it. Thanks.

**Comment by dan200** [comment]
Glad to hear it :) I've updated the game to give a clearer error message if
it happens again. Enjoy the game!
