### ISSUE TITLE
ComputerCraft Crash!!!

### ISSUE THREAD

**Issue by ghost** [dan200/Redirection#53]
This happen when i place down the disk drive and insert floppy disk then i place computer next to it and boom game crash.

I play on SkyFactory One Modpack.

This error on minecraft launcher.

The game crashed whilst ticking block entity
Error: java.lang.NoSuchMethodError: dan200.computercraft.api.peripheral.IPeripheral.getAdditionalTypes()Ljava/util/Set;
Exit Code: -1

Crash Report VVV
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 5/14/22 10:04 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: dan200.computercraft.api.peripheral.IPeripheral.getAdditionalTypes()Ljava/util/Set;
	at dan200.computercraft.core.apis.PeripheralAPI$PeripheralWrapper.<init>(PeripheralAPI.java:52) ~[?:1.99.0] {re:classloading}
	at dan200.computercraft.core.apis.PeripheralAPI.onPeripheralChanged(PeripheralAPI.java:234) ~[?:1.99.0] {re:classloading}
	at dan200.computercraft.core.computer.Environment.setPeripheral(Environment.java:317) ~[?:1.99.0] {re:classloading}
	at dan200.computercraft.shared.computer.core.ServerComputer.setPeripheral(ServerComputer.java:288) ~[?:1.99.0] {re:classloading}
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.refreshPeripheral(TileComputerBase.java:252) ~[?:1.99.0] {re:classloading}
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.updateInputsImmediately(TileComputerBase.java:276) ~[?:1.99.0] {re:classloading}
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.createServerComputer(TileComputerBase.java:378) ~[?:1.99.0] {re:classloading}
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_73660_a(TileComputerBase.java:159) ~[?:1.99.0] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.stevekung's_lib.json:server.level.MixinServerLevel,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$16821/465904941.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at dan200.computercraft.core.apis.PeripheralAPI$PeripheralWrapper.<init>(PeripheralAPI.java:52) ~[?:1.99.0] {re:classloading}
	at dan200.computercraft.core.apis.PeripheralAPI.onPeripheralChanged(PeripheralAPI.java:234) ~[?:1.99.0] {re:classloading}
	at dan200.computercraft.core.computer.Environment.setPeripheral(Environment.java:317) ~[?:1.99.0] {re:classloading}
	at dan200.computercraft.shared.computer.core.ServerComputer.setPeripheral(ServerComputer.java:288) ~[?:1.99.0] {re:classloading}
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.refreshPeripheral(TileComputerBase.java:252) ~[?:1.99.0] {re:classloading}
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.updateInputsImmediately(TileComputerBase.java:276) ~[?:1.99.0] {re:classloading}
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.createServerComputer(TileComputerBase.java:378) ~[?:1.99.0] {re:classloading}
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_73660_a(TileComputerBase.java:159) ~[?:1.99.0] {re:classloading}
-- Block entity being ticked --
Details:
	Name: computercraft:computer_normal // dan200.computercraft.shared.computer.blocks.TileComputer
	Block: Block{computercraft:computer_normal}[facing=south,state=off]
	Block location: World: (3,65,1), Chunk: (at 3,4,1 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Block: Block{computercraft:computer_normal}[facing=south,state=off]
	Block location: World: (3,65,1), Chunk: (at 3,4,1 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.stevekung's_lib.json:server.level.MixinServerLevel,pl:mixin:A}

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 2025
	Level dimension: minecraft:overworld
	Level spawn location: World: (2,71,2), Chunk: (at 2,4,2 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 497212 game time, 554851 day time
	Level name: Phu's SkyFactory
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 37440 (now: false), thunder time: 3609 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$16821/465904941.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 639228408 bytes (609 MB) / 3266838528 bytes (3115 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 4
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.20.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.20
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		SlabMachines-1.16.5-1.1.jar                       |Slab Machines                 |slabmachines                  |1.1                 |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.0.9-mc1.16.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.9               |DONE      |Manifest: NOSIGNATURE
		Hats-1.16.5-10.3.3.jar                            |Hats                          |hats                          |10.3.3              |DONE      |Manifest: NOSIGNATURE
		refinedpipes-0.5.jar                              |Refined Pipes                 |refinedpipes                  |0.5                 |DONE      |Manifest: NOSIGNATURE
		Uppers-0.3.2.jar                                  |Uppers                        |uppers                        |0.3.2               |DONE      |Manifest: NOSIGNATURE
		connectivity-2.4-1.16.5.jar                       |Connectivity Mod              |connectivity                  |2.4-1.16.5          |DONE      |Manifest: NOSIGNATURE
		modnametooltip_1.16.2-1.15.0.jar                  |Mod Name Tooltip              |modnametooltip                |1.15.0              |DONE      |Manifest: NOSIGNATURE
		findme-1.16.3-2.2.0.0.jar                         |Find Me                       |findme                        |2.2.0               |DONE      |Manifest: NOSIGNATURE
		CTM-MC1.16.1-1.1.2.6.jar                          |ConnectedTexturesMod          |ctm                           |MC1.16.1-1.1.2.6    |DONE      |Manifest: NOSIGNATURE
		Placebo-1.16.5-4.6.1.jar                          |Placebo                       |placebo                       |4.6.1               |DONE      |Manifest: NOSIGNATURE
		ColouredTooltips-1.16.5-11.0.3.jar                |ColouredTooltips              |colouredtooltips              |11.0.3              |DONE      |Manifest: NOSIGNATURE
		ChanceCubes-1.16.5-5.0.2.433.jar                  |Chance Cubes                  |chancecubes                   |1.16.5-5.0.2.433    |DONE      |Manifest: NOSIGNATURE
		ExCompressum_1.16.5-4.0.5.jar                     |Ex Compressum                 |excompressum                  |4.0.5               |DONE      |Manifest: NOSIGNATURE
		forcecraft-1.16.5-1.0.8.3.jar                     |ForceCraft                    |forcecraft                    |1.0.8.3             |DONE      |Manifest: NOSIGNATURE
		Apotheosis-1.16.5-4.8.3.jar                       |Apotheosis                    |apotheosis                    |4.8.3               |DONE      |Manifest: NOSIGNATURE
		TwerkItMeal-1.3.9.jar                             |TwerkItMeal                   |twerkitmeal                   |1.3.9               |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.16.5-0.17.9.jar                 |Supplementaries               |supplementaries               |1.16.5-0.17.9       |DONE      |Manifest: NOSIGNATURE
		mob_grinding_utils-1.16.5-0.4.30.jar              |Mob Grinding Utils            |mob_grinding_utils            |1.16.5-0.4.30       |DONE      |Manifest: NOSIGNATURE
		refinedstorage-1.9.16.jar                         |Refined Storage               |refinedstorage                |1.9.16              |DONE      |Manifest: NOSIGNATURE
		PackMenu-1.16.5-2.5.0.jar                         |PackMenu                      |packmenu                      |2.5.0               |DONE      |Manifest: NOSIGNATURE
		industrial-foregoing-1.16.5-3.2.14.7-16.jar       |Industrial Foregoing          |industrialforegoing           |3.2.14.7            |DONE      |Manifest: NOSIGNATURE
		torchmaster-2.3.8.jar                             |Torchmaster                   |torchmaster                   |2.3.8               |DONE      |Manifest: NOSIGNATURE
		entangled-1.3.9-mc1.16.jar                        |Entangled                     |entangled                     |1.3.9               |DONE      |Manifest: NOSIGNATURE
		Compressium-1.16.5-1.2.3.jar                      |Compressium                   |compressium                   |1.2.custom          |DONE      |Manifest: NOSIGNATURE
		plaingrinder-1.16.5-1.2.1.jar                     |plaingrinder                  |plaingrinder                  |1.16.5-1.2.1        |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		valkyrielib-1.16.5-3.0.9.5.jar                    |ValkyrieLib                   |valkyrielib                   |1.16.5-3.0.9.5      |DONE      |Manifest: NOSIGNATURE
		drawerfps-2.1.jar                                 |Drawer FPS                    |drawerfps                     |2.1                 |DONE      |Manifest: NOSIGNATURE
		DarkoHud-1.16.5-1.0.3.jar                         |Darko HUD                     |darkohud                      |1.0.3               |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.14a-mc1.16.5.jar       |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.14a             |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.2.jar                         |Patchouli                     |patchouli                     |1.16.4-53.2         |DONE      |Manifest: NOSIGNATURE
		collective-1.16.5-2.65.jar                        |Collective                    |collective                    |2.65                |DONE      |Manifest: NOSIGNATURE
		OreExcavation-1.8.157.jar                         |Ore Excavation                |oreexcavation                 |1.8.157             |DONE      |Manifest: e7:68:1c:0d:b9:7e:cf:f8:f3:40:9c:84:c5:39:d7:a4:59:78:b0:6b:c3:fd:b7:4f:69:18:a3:88:e3:76:8c:3f
		Measurements-1.16.5-1.2.jar                       |Measurements                  |measurements                  |1.2                 |DONE      |Manifest: NOSIGNATURE
		FramedBlocks-2.11.2.jar                           |FramedBlocks                  |framedblocks                  |2.11.2              |DONE      |Manifest: NOSIGNATURE
		simplegens-1.16.5-3.0.9.2.jar                     |Simple Generators             |simplegens                    |1.16.5-3.0.9.2      |DONE      |Manifest: NOSIGNATURE
		elevatorid-1.16.5-1.7.13.jar                      |Elevator Mod                  |elevatorid                    |1.16.5-1.7.13       |DONE      |Manifest: NOSIGNATURE
		buildersaddition-1.16.5-20210807a.jar             |Builders Crafts & Addition    |buildersaddition              |1.16.5-20210807a    |DONE      |Manifest: NOSIGNATURE
		Attained-Drops-1.16.4-7.2.2.jar                   |Attained Drops                |attained_drops                |7.2.2               |DONE      |Manifest: NOSIGNATURE
		starterkit_1.16.5-2.5.jar                         |Starter Kit                   |starterkit                    |2.5                 |DONE      |Manifest: NOSIGNATURE
		constructionwand-1.16.5-2.4.jar                   |Construction Wand             |constructionwand              |1.16.5-2.4          |DONE      |Manifest: NOSIGNATURE
		Checklist-1.16.5-1.2.2.jar                        |Checklist                     |checklist                     |1.2.2               |DONE      |Manifest: NOSIGNATURE
		architectury-1.24.35-forge.jar                    |Architectury                  |architectury                  |1.24.35             |DONE      |Manifest: NOSIGNATURE
		cc-tweaked-1.16.5-1.99.0.jar                      |CC: Tweaked                   |computercraft                 |1.99.0              |DONE      |Manifest: NOSIGNATURE
		moreoverlays-1.18.17-mc1.16.5.jar                 |More Overlays Updated         |moreoverlays                  |1.18.17-mc1.16.5    |DONE      |Manifest: NOSIGNATURE
		chunkloaders-1.1.7-mc1.16.5.jar                   |Chunk Loaders                 |chunkloaders                  |1.1.7               |DONE      |Manifest: NOSIGNATURE
		CobbleForDays-1.3.7.jar                           |Cobble For Days               |cobblefordays                 |1.3.7               |DONE      |Manifest: NOSIGNATURE
		CodeChickenLib-1.16.5-4.0.5.438-universal.jar     |CodeChicken Lib               |codechickenlib                |4.0.5.438           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		Cyclic-1.16.5-1.5.11.jar                          |Cyclic                        |cyclic                        |1.16.5-1.5.11       |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		SpawnsInSpawn-1.16.5-1.0.0.jar                    |Spawns In Spawn               |spawnsinspawn                 |1.0.0               |DONE      |Manifest: NOSIGNATURE
		Cucumber-1.16.5-4.1.12.jar                        |Cucumber Library              |cucumber                      |4.1.12              |DONE      |Manifest: NOSIGNATURE
		tesseract-1.0.24-mc1.16.jar                       |Tesseract                     |tesseract                     |1.0.24              |DONE      |Manifest: NOSIGNATURE
		FastSuite-1.16.4-1.1.1.jar                        |FastSuite                     |fastsuite                     |1.1.1               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.7.3.jar                       |Journeymap                    |journeymap                    |5.7.3               |DONE      |Manifest: NOSIGNATURE
		Artifacts-1.16.5-2.10.3.jar                       |Artifacts                     |artifacts                     |1.16.5-2.10.3       |DONE      |Manifest: NOSIGNATURE
		SpawnNormalization-1.16.5-1.0.1.jar               |Spawn Normalization           |spawnnorms                    |1.0.1               |DONE      |Manifest: NOSIGNATURE
		LibX-1.16.3-1.0.76.jar                            |LibX                          |libx                          |1.16.3-1.0.76       |DONE      |Manifest: NOSIGNATURE
		angelblock-3.0.jar                                |Angel Block                   |angelblock                    |3.0                 |DONE      |Manifest: NOSIGNATURE
		topography-1.17.2.jar                             |Topography                    |topography                    |1.17.2              |DONE      |Manifest: NOSIGNATURE
		mcjtylib-1.16-5.0.23.jar                          |McJtyLib                      |mcjtylib                      |1.16-5.0.23         |DONE      |Manifest: NOSIGNATURE
		rftoolsbase-1.16-2.0.11.jar                       |RFToolsBase                   |rftoolsbase                   |1.16-2.0.11         |DONE      |Manifest: NOSIGNATURE
		TelePastries-1.16.5-0.4.3.jar                     |TelePastries                  |telepastries                  |0.4.3               |DONE      |Manifest: NOSIGNATURE
		ClickMachine-1.16.5-4.5.0.jar                     |Click Machine                 |clickmachine                  |4.5.0               |DONE      |Manifest: NOSIGNATURE
		walljump-forge-1.16.4-1.3.7.jar                   |Wall-Jump!                    |walljump                      |1.16.4-1.3.7        |DONE      |Manifest: NOSIGNATURE
		ToastControl-1.16.5-4.4.0.jar                     |Toast Control                 |toastcontrol                  |4.4.0               |DONE      |Manifest: NOSIGNATURE
		iChunUtil-1.16.5-10.5.1.jar                       |iChunUtil                     |ichunutil                     |10.5.1              |DONE      |Manifest: NOSIGNATURE
		InfoDataPack-1.16.5-1.0.2.jar                     |Info DataPack                 |infodatapack                  |1.0.2               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.137.jar                          |Just Enough Items             |jei                           |7.7.1.137           |DONE      |Manifest: NOSIGNATURE
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |DONE      |Manifest: NOSIGNATURE
		EnderStorage-1.16.5-2.8.0.168-universal.jar       |EnderStorage                  |enderstorage                  |2.8.0.168           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		SteveKunG's-Lib-mc1.16.5-v4.1.6-forge.jar         |SteveKunG's Lib               |stevekungs_lib                |4.1.6               |DONE      |Manifest: NOSIGNATURE
		rftoolspower-1.16-3.0.9.jar                       |RFToolsPower                  |rftoolspower                  |1.16-3.0.9          |DONE      |Manifest: NOSIGNATURE
		BlockDiversity-1.16.5-1.3.2.jar                   |Block Diversity               |buildersplus                  |1.3.2               |DONE      |Manifest: NOSIGNATURE
		crumbs-forge-1.0.7.jar                            |Crumbs                        |crumbs                        |1.0.7               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.20-universal.jar                |Forge                         |forge                         |36.2.20             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		simpletomb-1.16.5-1.0.9.jar                       |Simple Tombstone              |simpletomb                    |1.16.5-1.0.9        |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		selene-1.16.5-1.9.0.jar                           |Selene                        |selene                        |1.16.5-1.0          |DONE      |Manifest: NOSIGNATURE
		MysticalAgriculture-1.16.5-4.2.5.jar              |Mystical Agriculture          |mysticalagriculture           |4.2.5               |DONE      |Manifest: NOSIGNATURE
		ironchest-1.16.5-11.2.13.jar                      |Iron Chests                   |ironchest                     |1.16.5-11.2.13      |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.20-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		cofh_core-1.16.5-1.3.1.jar                        |CoFH Core                     |cofh_core                     |1.3.1               |DONE      |Manifest: NOSIGNATURE
		thermal_foundation-1.16.5-1.3.2.jar               |Thermal Series                |thermal                       |1.3.2               |DONE      |Manifest: NOSIGNATURE
		thermal_innovation-1.16.5-1.3.0.jar               |Thermal Innovation            |thermal_innovation            |1.3.0               |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_expansion-1.16.5-1.3.0.jar                |Thermal Expansion             |thermal_expansion             |1.3.0               |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		exnihilothermal-1.16-1.0.0.0.jar                  |Ex Nihilo: Sequentia - Thermal|exnihilothermal               |1.16-1.0.0.0        |DONE      |Manifest: NOSIGNATURE
		TConstruct-1.16.5-3.2.1.296.jar                   |Tinkers' Construct            |tconstruct                    |3.2.1.296           |DONE      |Manifest: NOSIGNATURE
		theoneprobe-1.16-3.1.4.jar                        |The One Probe                 |theoneprobe                   |1.16-3.1.4          |DONE      |Manifest: NOSIGNATURE
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |DONE      |Manifest: NOSIGNATURE
		titanium-1.16.5-3.2.8.7-22.jar                    |Titanium                      |titanium                      |3.2.8.7             |DONE      |Manifest: NOSIGNATURE
		minis-1.16.5-1.6+11.jar                           |Minis                         |minis                         |1.16.5-1.6+11       |DONE      |Manifest: NOSIGNATURE
		rftoolsbuilder-1.16-3.1.2.jar                     |RFToolsBuilder                |rftoolsbuilder                |1.16-3.1.2          |DONE      |Manifest: NOSIGNATURE
		pipez-1.16.5-1.2.14.jar                           |Pipez                         |pipez                         |1.16.5-1.2.14       |DONE      |Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.127.jar                         |Mantle                        |mantle                        |1.6.127             |DONE      |Manifest: NOSIGNATURE
		Inspirations-1.16.5-1.2.3.38.jar                  |Inspirations                  |inspirations                  |1.2.3.38            |DONE      |Manifest: NOSIGNATURE
		itemcollectors-1.1.3-mc1.16.jar                   |Item Collectors               |itemcollectors                |1.1.3               |DONE      |Manifest: NOSIGNATURE
		DarkoHacksRP-1.16.4-1.0.4.jar                     |DarkoHaxRP                    |darkohax2                     |1.0.4               |DONE      |Manifest: NOSIGNATURE
		thermal_cultivation-1.16.5-1.3.0.jar              |Thermal Cultivation           |thermal_cultivation           |1.3.0               |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		serverconfigupdater-1.3.jar                       |ServerConfig Updater          |serverconfigupdater           |1.3                 |DONE      |Manifest: NOSIGNATURE
		FastWorkbench-1.16.5-4.6.0.jar                    |Fast Workbench                |fastbench                     |4.6.0               |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.16.3-8.3.0.jar                   |Storage Drawers               |storagedrawers                |8.3.0               |DONE      |Manifest: NOSIGNATURE
		Statues-1.16.5-0.1.7.5.jar                        |Statues Mod                   |statues                       |0.1.7.5             |DONE      |Manifest: NOSIGNATURE
		globaldataandresourcepacks-1.16.5-1.10.2.jar      |Global Data- & Resourcepacks  |globaldataandresourcepacks    |1.10.2              |DONE      |Manifest: NOSIGNATURE
		PickleTweaks-1.16.5-5.2.6.jar                     |Pickle Tweaks                 |pickletweaks                  |5.2.6               |DONE      |Manifest: NOSIGNATURE
		FastFurnace-1.16.5-4.5.0.jar                      |FastFurnace                   |fastfurnace                   |4.5.0               |DONE      |Manifest: NOSIGNATURE
		Bongo-1.16.5-1.3.0.jar                            |Bongo                         |bongo                         |1.16.5-1.3.0        |DONE      |Manifest: NOSIGNATURE
		refinedstorageaddons-0.7.4.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.7.4               |DONE      |Manifest: NOSIGNATURE
		expandability-2.0.1-forge.jar                     |ExpandAbility                 |expandability                 |2.0.1               |DONE      |Manifest: NOSIGNATURE
		exnihilotinkers-1.16-1.0.0.0.jar                  |Ex Nihilo: Sequentia - Tinkers|exnihilotinkers               |1.16-1.0.0.0        |DONE      |Manifest: NOSIGNATURE
		exnihilosequentia-1.16-20211123-032540.jar        |Ex Nihilo: Sequentia          |exnihilosequentia             |1.16-20211123-032540|DONE      |Manifest: NOSIGNATURE
		DefaultOptions_1.16.5-12.2.1.jar                  |Default Options               |defaultoptions                |12.2.1              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 57968a61-d7f3-44df-a39c-196ba92dac6e
	Patchouli open book context: n/a
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:slabmachines, mod:supermartijn642configlib, mod:hats, mod:refinedpipes, mod:uppers (incompatible), mod:connectivity, mod:modnametooltip, mod:findme (incompatible), mod:ctm (incompatible), mod:placebo (incompatible), mod:colouredtooltips, mod:chancecubes (incompatible), mod:excompressum (incompatible), mod:forcecraft, mod:apotheosis (incompatible), mod:twerkitmeal, mod:supplementaries, mod:mob_grinding_utils, mod:refinedstorage, mod:packmenu (incompatible), mod:industrialforegoing (incompatible), mod:torchmaster (incompatible), mod:entangled, mod:compressium (incompatible), mod:plaingrinder, mod:valkyrielib, mod:drawerfps, mod:darkohud (incompatible), mod:supermartijn642corelib, mod:curios, mod:patchouli (incompatible), mod:collective, mod:oreexcavation, mod:measurements, mod:framedblocks (incompatible), mod:simplegens, mod:elevatorid, mod:buildersaddition (incompatible), mod:attained_drops (incompatible), mod:starterkit, mod:constructionwand (incompatible), mod:checklist, mod:architectury, mod:computercraft, mod:moreoverlays, mod:chunkloaders, mod:cobblefordays (incompatible), mod:codechickenlib (incompatible), mod:cyclic (incompatible), mod:spawnsinspawn (incompatible), mod:cucumber, mod:tesseract, mod:fastsuite (incompatible), mod:journeymap (incompatible), mod:artifacts, mod:spawnnorms (incompatible), mod:libx, mod:angelblock (incompatible), mod:topography (incompatible), mod:mcjtylib, mod:rftoolsbase, mod:telepastries, mod:clickmachine (incompatible), mod:walljump (incompatible), mod:toastcontrol (incompatible), mod:ichunutil, mod:infodatapack, mod:jei, mod:invtweaks (incompatible), mod:enderstorage (incompatible), mod:stevekungs_lib, mod:rftoolspower, mod:buildersplus, mod:crumbs, mod:forge, mod:simpletomb, mod:selene, mod:mysticalagriculture, mod:ironchest, mod:cofh_core (incompatible), mod:thermal (incompatible), mod:thermal_innovation (incompatible), mod:thermal_expansion (incompatible), mod:exnihilothermal, mod:tconstruct, mod:theoneprobe, mod:swingthroughgrass (incompatible), mod:mousetweaks, mod:titanium (incompatible), mod:minis, mod:rftoolsbuilder, mod:pipez, mod:mantle (incompatible), mod:inspirations (incompatible), mod:itemcollectors, mod:darkohax2 (incompatible), mod:thermal_cultivation (incompatible), mod:serverconfigupdater (incompatible), mod:fastbench (incompatible), mod:storagedrawers (incompatible), mod:statues, mod:globaldataandresourcepacks (incompatible), mod:pickletweaks, mod:fastfurnace (incompatible), mod:bongo (incompatible), mod:refinedstorageaddons, mod:expandability, mod:exnihilotinkers, mod:exnihilosequentia, mod:defaultoptions (incompatible), global:bingo, global:skyfactoryone
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by dan200** [comment]
This repository is for Redirection, not ComputerCraft!

**Comment by ghost** [comment]
Oh sorry 😢
